rank(naruto, genin).
rank(kiba, chuunin).
rank(rocklee, chuunin).
rank(kakashi, jounin).
rank(itachi, jounin).
rank(gaara, kage).
rank(temari, jounin).
rank(kankuro, jounin).
rank(hidan, jounin).
rank(kisame, jounin).
rank(dzhiraya, sanin).
rank(orachimaru, sanin).
rank(haku, none).
rank(zabuza, jounin).
rank(suigetsu, chuunin).
rank(sai, chuubu).
rank(deidara, jounin).
rank(sakura, chuunin).
rank(hinata, chuunin).
rank(tenten, chuunin).

village(naruto, leaf).
village(kiba, leaf).
village(rocklee, leaf).
village(kakashi, leaf).
village(itachi, leaf).
village(gaara, sand).
village(temari, sand).
village(kankuro, sand).
village(hidan, springs).
village(kisame, fog).
village(dzhiraya, leaf).
village(orachimaru, leaf).
village(haku, none).
village(zabuza, fog).
village(suigetsu, fog).
village(sai, leaf).
village(deidara, rock).
village(sakura, leaf).
village(hinata, leaf).
village(tenten, leaf).

jutsu(naruto, ninjutsu).
jutsu(kiba, ninjutsu).
jutsu(rocklee, taijutsu).
jutsu(kakashi, ninjutsu).
jutsu(itachi, genjutsu).
jutsu(gaara, ninjutsu).
jutsu(temari, ninjutsu).
jutsu(kankuro, ninjutsu).
jutsu(hidan, kinjutsu).
jutsu(kisame, kenjutsu).
jutsu(dzhiraya, ninjutsu).
jutsu(orachimaru, kinjutsu).
jutsu(haku, ninjutsu).
jutsu(zabuza, kenjutsu).
jutsu(suigetsu, kenjutsu).
jutsu(sai, ninjutsu).
jutsu(deidara, ninjutsu).
jutsu(sakura, medic).
jutsu(hinata, doujutsu).
jutsu(tenten, shurikenjutsu).

element(naruto, wind).
element(kiba, soil).
element(rocklee, none).
element(kakashi, lighting).
element(itachi, fire).
element(gaara, soil).
element(temari, wind).
element(kankuro, yan).
element(hidan, none).
element(kisame, water).
element(dzhiraya, water).
element(orachimaru, water).
element(haku, water).
element(zabuza, water).
element(suigetsu, water).
element(sai, yan).
element(deidara, yan).
element(sakura, yan).
element(hinata, wind).
element(tenten, wind).

kekkei(naruto, biju).
kekkei(kiba, none).
kekkei(rocklee, none).
kekkei(kakashi, none).
kekkei(itachi, sharingan).
kekkei(gaara, biju).
kekkei(temari, none).
kekkei(kankuro, none).
kekkei(hidan, none).
kekkei(kisame, none).
kekkei(dzhiraya, none).
kekkei(orachimaru, none).
kekkei(haku, ice).
kekkei(zabuza, none).
kekkei(suigetsu, none).
kekkei(sai, none).
kekkei(deidara, explosion).
kekkei(sakura, none).
kekkei(hinata, byakugan).
kekkei(tenten, none).

organization(itachi, akatsuki).
organization(hidan, akatsuki).
organization(kisame, akatsuki).
organization(sai, anbu).
organization(deidara, akatsuki).
